/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentScheduleRouteImport } from './routes/student-schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudentWelzijnRouteImport } from './routes/_app.student-welzijn'
import { Route as AppStudentProgressRouteImport } from './routes/_app.student-progress'
import { Route as AppStudentProfileSettingsRouteImport } from './routes/_app.student-profile-settings'
import { Route as AppStudentPlannerRouteImport } from './routes/_app.student-planner'
import { Route as AppStudentNotesRouteImport } from './routes/_app.student-notes'
import { Route as AppStudentDashboardRouteImport } from './routes/_app.student-dashboard'
import { Route as AppStudentCoursesRouteImport } from './routes/_app.student-courses'
import { Route as AppStudentAchievementsRouteImport } from './routes/_app.student-achievements'
import { Route as AppFocusTimerRouteImport } from './routes/_app.focus-timer'
import { Route as SrcRoutesLoginRouteImport } from './routes/src/routes/login'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/student-schedule',
  path: '/student-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentWelzijnRoute = AppStudentWelzijnRouteImport.update({
  id: '/student-welzijn',
  path: '/student-welzijn',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentProgressRoute = AppStudentProgressRouteImport.update({
  id: '/student-progress',
  path: '/student-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentProfileSettingsRoute =
  AppStudentProfileSettingsRouteImport.update({
    id: '/student-profile-settings',
    path: '/student-profile-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentPlannerRoute = AppStudentPlannerRouteImport.update({
  id: '/student-planner',
  path: '/student-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentNotesRoute = AppStudentNotesRouteImport.update({
  id: '/student-notes',
  path: '/student-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentDashboardRoute = AppStudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/student-courses',
  path: '/student-courses',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentAchievementsRoute = AppStudentAchievementsRouteImport.update({
  id: '/student-achievements',
  path: '/student-achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusTimerRoute = AppFocusTimerRouteImport.update({
  id: '/focus-timer',
  path: '/focus-timer',
  getParentRoute: () => AppRoute,
} as any)
const SrcRoutesLoginRoute = SrcRoutesLoginRouteImport.update({
  id: '/src/routes/login',
  path: '/src/routes/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/focus-timer': typeof AppFocusTimerRoute
  '/student-achievements': typeof AppStudentAchievementsRoute
  '/student-courses': typeof AppStudentCoursesRoute
  '/student-dashboard': typeof AppStudentDashboardRoute
  '/student-notes': typeof AppStudentNotesRoute
  '/student-planner': typeof AppStudentPlannerRoute
  '/student-profile-settings': typeof AppStudentProfileSettingsRoute
  '/student-progress': typeof AppStudentProgressRoute
  '/student-welzijn': typeof AppStudentWelzijnRoute
  '/src/routes/login': typeof SrcRoutesLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/focus-timer': typeof AppFocusTimerRoute
  '/student-achievements': typeof AppStudentAchievementsRoute
  '/student-courses': typeof AppStudentCoursesRoute
  '/student-dashboard': typeof AppStudentDashboardRoute
  '/student-notes': typeof AppStudentNotesRoute
  '/student-planner': typeof AppStudentPlannerRoute
  '/student-profile-settings': typeof AppStudentProfileSettingsRoute
  '/student-progress': typeof AppStudentProgressRoute
  '/student-welzijn': typeof AppStudentWelzijnRoute
  '/src/routes/login': typeof SrcRoutesLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/_app/focus-timer': typeof AppFocusTimerRoute
  '/_app/student-achievements': typeof AppStudentAchievementsRoute
  '/_app/student-courses': typeof AppStudentCoursesRoute
  '/_app/student-dashboard': typeof AppStudentDashboardRoute
  '/_app/student-notes': typeof AppStudentNotesRoute
  '/_app/student-planner': typeof AppStudentPlannerRoute
  '/_app/student-profile-settings': typeof AppStudentProfileSettingsRoute
  '/_app/student-progress': typeof AppStudentProgressRoute
  '/_app/student-welzijn': typeof AppStudentWelzijnRoute
  '/src/routes/login': typeof SrcRoutesLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/focus-timer'
    | '/student-achievements'
    | '/student-courses'
    | '/student-dashboard'
    | '/student-notes'
    | '/student-planner'
    | '/student-profile-settings'
    | '/student-progress'
    | '/student-welzijn'
    | '/src/routes/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/focus-timer'
    | '/student-achievements'
    | '/student-courses'
    | '/student-dashboard'
    | '/student-notes'
    | '/student-planner'
    | '/student-profile-settings'
    | '/student-progress'
    | '/student-welzijn'
    | '/src/routes/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/_app/focus-timer'
    | '/_app/student-achievements'
    | '/_app/student-courses'
    | '/_app/student-dashboard'
    | '/_app/student-notes'
    | '/_app/student-planner'
    | '/_app/student-profile-settings'
    | '/_app/student-progress'
    | '/_app/student-welzijn'
    | '/src/routes/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  TeacherRoute: typeof TeacherRoute
  SrcRoutesLoginRoute: typeof SrcRoutesLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-schedule': {
      id: '/student-schedule'
      path: '/student-schedule'
      fullPath: '/student-schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/student-welzijn': {
      id: '/_app/student-welzijn'
      path: '/student-welzijn'
      fullPath: '/student-welzijn'
      preLoaderRoute: typeof AppStudentWelzijnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-progress': {
      id: '/_app/student-progress'
      path: '/student-progress'
      fullPath: '/student-progress'
      preLoaderRoute: typeof AppStudentProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-profile-settings': {
      id: '/_app/student-profile-settings'
      path: '/student-profile-settings'
      fullPath: '/student-profile-settings'
      preLoaderRoute: typeof AppStudentProfileSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-planner': {
      id: '/_app/student-planner'
      path: '/student-planner'
      fullPath: '/student-planner'
      preLoaderRoute: typeof AppStudentPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-notes': {
      id: '/_app/student-notes'
      path: '/student-notes'
      fullPath: '/student-notes'
      preLoaderRoute: typeof AppStudentNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-dashboard': {
      id: '/_app/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof AppStudentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-courses': {
      id: '/_app/student-courses'
      path: '/student-courses'
      fullPath: '/student-courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-achievements': {
      id: '/_app/student-achievements'
      path: '/student-achievements'
      fullPath: '/student-achievements'
      preLoaderRoute: typeof AppStudentAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/focus-timer': {
      id: '/_app/focus-timer'
      path: '/focus-timer'
      fullPath: '/focus-timer'
      preLoaderRoute: typeof AppFocusTimerRouteImport
      parentRoute: typeof AppRoute
    }
    '/src/routes/login': {
      id: '/src/routes/login'
      path: '/src/routes/login'
      fullPath: '/src/routes/login'
      preLoaderRoute: typeof SrcRoutesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppFocusTimerRoute: typeof AppFocusTimerRoute
  AppStudentAchievementsRoute: typeof AppStudentAchievementsRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRoute
  AppStudentDashboardRoute: typeof AppStudentDashboardRoute
  AppStudentNotesRoute: typeof AppStudentNotesRoute
  AppStudentPlannerRoute: typeof AppStudentPlannerRoute
  AppStudentProfileSettingsRoute: typeof AppStudentProfileSettingsRoute
  AppStudentProgressRoute: typeof AppStudentProgressRoute
  AppStudentWelzijnRoute: typeof AppStudentWelzijnRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFocusTimerRoute: AppFocusTimerRoute,
  AppStudentAchievementsRoute: AppStudentAchievementsRoute,
  AppStudentCoursesRoute: AppStudentCoursesRoute,
  AppStudentDashboardRoute: AppStudentDashboardRoute,
  AppStudentNotesRoute: AppStudentNotesRoute,
  AppStudentPlannerRoute: AppStudentPlannerRoute,
  AppStudentProfileSettingsRoute: AppStudentProfileSettingsRoute,
  AppStudentProgressRoute: AppStudentProgressRoute,
  AppStudentWelzijnRoute: AppStudentWelzijnRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  TeacherRoute: TeacherRoute,
  SrcRoutesLoginRoute: SrcRoutesLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
