/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentScheduleRouteImport } from './routes/student-schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StudentAppRouteImport } from './routes/_studentApp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as StudentAppStudentWelzijnRouteImport } from './routes/_studentApp.student-welzijn'
import { Route as StudentAppStudentProgressRouteImport } from './routes/_studentApp.student-progress'
import { Route as StudentAppStudentProfileSettingsRouteImport } from './routes/_studentApp.student-profile-settings'
import { Route as StudentAppStudentPlannerRouteImport } from './routes/_studentApp.student-planner'
import { Route as StudentAppStudentNotesRouteImport } from './routes/_studentApp.student-notes'
import { Route as StudentAppStudentDashboardRouteImport } from './routes/_studentApp.student-dashboard'
import { Route as StudentAppStudentCoursesRouteImport } from './routes/_studentApp.student-courses'
import { Route as StudentAppStudentAchievementsRouteImport } from './routes/_studentApp.student-achievements'
import { Route as StudentAppFocusTimerRouteImport } from './routes/_studentApp.focus-timer'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/student-schedule',
  path: '/student-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAppRoute = StudentAppRouteImport.update({
  id: '/_studentApp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StudentAppStudentWelzijnRoute =
  StudentAppStudentWelzijnRouteImport.update({
    id: '/student-welzijn',
    path: '/student-welzijn',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentProgressRoute =
  StudentAppStudentProgressRouteImport.update({
    id: '/student-progress',
    path: '/student-progress',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentProfileSettingsRoute =
  StudentAppStudentProfileSettingsRouteImport.update({
    id: '/student-profile-settings',
    path: '/student-profile-settings',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentPlannerRoute =
  StudentAppStudentPlannerRouteImport.update({
    id: '/student-planner',
    path: '/student-planner',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentNotesRoute = StudentAppStudentNotesRouteImport.update({
  id: '/student-notes',
  path: '/student-notes',
  getParentRoute: () => StudentAppRoute,
} as any)
const StudentAppStudentDashboardRoute =
  StudentAppStudentDashboardRouteImport.update({
    id: '/student-dashboard',
    path: '/student-dashboard',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentCoursesRoute =
  StudentAppStudentCoursesRouteImport.update({
    id: '/student-courses',
    path: '/student-courses',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppStudentAchievementsRoute =
  StudentAppStudentAchievementsRouteImport.update({
    id: '/student-achievements',
    path: '/student-achievements',
    getParentRoute: () => StudentAppRoute,
  } as any)
const StudentAppFocusTimerRoute = StudentAppFocusTimerRouteImport.update({
  id: '/focus-timer',
  path: '/focus-timer',
  getParentRoute: () => StudentAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/focus-timer': typeof StudentAppFocusTimerRoute
  '/student-achievements': typeof StudentAppStudentAchievementsRoute
  '/student-courses': typeof StudentAppStudentCoursesRoute
  '/student-dashboard': typeof StudentAppStudentDashboardRoute
  '/student-notes': typeof StudentAppStudentNotesRoute
  '/student-planner': typeof StudentAppStudentPlannerRoute
  '/student-profile-settings': typeof StudentAppStudentProfileSettingsRoute
  '/student-progress': typeof StudentAppStudentProgressRoute
  '/student-welzijn': typeof StudentAppStudentWelzijnRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/focus-timer': typeof StudentAppFocusTimerRoute
  '/student-achievements': typeof StudentAppStudentAchievementsRoute
  '/student-courses': typeof StudentAppStudentCoursesRoute
  '/student-dashboard': typeof StudentAppStudentDashboardRoute
  '/student-notes': typeof StudentAppStudentNotesRoute
  '/student-planner': typeof StudentAppStudentPlannerRoute
  '/student-profile-settings': typeof StudentAppStudentProfileSettingsRoute
  '/student-progress': typeof StudentAppStudentProgressRoute
  '/student-welzijn': typeof StudentAppStudentWelzijnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_studentApp': typeof StudentAppRouteWithChildren
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/student-schedule': typeof StudentScheduleRoute
  '/teacher': typeof TeacherRoute
  '/_studentApp/focus-timer': typeof StudentAppFocusTimerRoute
  '/_studentApp/student-achievements': typeof StudentAppStudentAchievementsRoute
  '/_studentApp/student-courses': typeof StudentAppStudentCoursesRoute
  '/_studentApp/student-dashboard': typeof StudentAppStudentDashboardRoute
  '/_studentApp/student-notes': typeof StudentAppStudentNotesRoute
  '/_studentApp/student-planner': typeof StudentAppStudentPlannerRoute
  '/_studentApp/student-profile-settings': typeof StudentAppStudentProfileSettingsRoute
  '/_studentApp/student-progress': typeof StudentAppStudentProgressRoute
  '/_studentApp/student-welzijn': typeof StudentAppStudentWelzijnRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/focus-timer'
    | '/student-achievements'
    | '/student-courses'
    | '/student-dashboard'
    | '/student-notes'
    | '/student-planner'
    | '/student-profile-settings'
    | '/student-progress'
    | '/student-welzijn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/focus-timer'
    | '/student-achievements'
    | '/student-courses'
    | '/student-dashboard'
    | '/student-notes'
    | '/student-planner'
    | '/student-profile-settings'
    | '/student-progress'
    | '/student-welzijn'
  id:
    | '__root__'
    | '/_app'
    | '/_studentApp'
    | '/admin'
    | '/change-password'
    | '/login'
    | '/student-schedule'
    | '/teacher'
    | '/_studentApp/focus-timer'
    | '/_studentApp/student-achievements'
    | '/_studentApp/student-courses'
    | '/_studentApp/student-dashboard'
    | '/_studentApp/student-notes'
    | '/_studentApp/student-planner'
    | '/_studentApp/student-profile-settings'
    | '/_studentApp/student-progress'
    | '/_studentApp/student-welzijn'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  StudentAppRoute: typeof StudentAppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-schedule': {
      id: '/student-schedule'
      path: '/student-schedule'
      fullPath: '/student-schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studentApp': {
      id: '/_studentApp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_studentApp/student-welzijn': {
      id: '/_studentApp/student-welzijn'
      path: '/student-welzijn'
      fullPath: '/student-welzijn'
      preLoaderRoute: typeof StudentAppStudentWelzijnRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-progress': {
      id: '/_studentApp/student-progress'
      path: '/student-progress'
      fullPath: '/student-progress'
      preLoaderRoute: typeof StudentAppStudentProgressRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-profile-settings': {
      id: '/_studentApp/student-profile-settings'
      path: '/student-profile-settings'
      fullPath: '/student-profile-settings'
      preLoaderRoute: typeof StudentAppStudentProfileSettingsRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-planner': {
      id: '/_studentApp/student-planner'
      path: '/student-planner'
      fullPath: '/student-planner'
      preLoaderRoute: typeof StudentAppStudentPlannerRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-notes': {
      id: '/_studentApp/student-notes'
      path: '/student-notes'
      fullPath: '/student-notes'
      preLoaderRoute: typeof StudentAppStudentNotesRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-dashboard': {
      id: '/_studentApp/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentAppStudentDashboardRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-courses': {
      id: '/_studentApp/student-courses'
      path: '/student-courses'
      fullPath: '/student-courses'
      preLoaderRoute: typeof StudentAppStudentCoursesRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/student-achievements': {
      id: '/_studentApp/student-achievements'
      path: '/student-achievements'
      fullPath: '/student-achievements'
      preLoaderRoute: typeof StudentAppStudentAchievementsRouteImport
      parentRoute: typeof StudentAppRoute
    }
    '/_studentApp/focus-timer': {
      id: '/_studentApp/focus-timer'
      path: '/focus-timer'
      fullPath: '/focus-timer'
      preLoaderRoute: typeof StudentAppFocusTimerRouteImport
      parentRoute: typeof StudentAppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StudentAppRouteChildren {
  StudentAppFocusTimerRoute: typeof StudentAppFocusTimerRoute
  StudentAppStudentAchievementsRoute: typeof StudentAppStudentAchievementsRoute
  StudentAppStudentCoursesRoute: typeof StudentAppStudentCoursesRoute
  StudentAppStudentDashboardRoute: typeof StudentAppStudentDashboardRoute
  StudentAppStudentNotesRoute: typeof StudentAppStudentNotesRoute
  StudentAppStudentPlannerRoute: typeof StudentAppStudentPlannerRoute
  StudentAppStudentProfileSettingsRoute: typeof StudentAppStudentProfileSettingsRoute
  StudentAppStudentProgressRoute: typeof StudentAppStudentProgressRoute
  StudentAppStudentWelzijnRoute: typeof StudentAppStudentWelzijnRoute
}

const StudentAppRouteChildren: StudentAppRouteChildren = {
  StudentAppFocusTimerRoute: StudentAppFocusTimerRoute,
  StudentAppStudentAchievementsRoute: StudentAppStudentAchievementsRoute,
  StudentAppStudentCoursesRoute: StudentAppStudentCoursesRoute,
  StudentAppStudentDashboardRoute: StudentAppStudentDashboardRoute,
  StudentAppStudentNotesRoute: StudentAppStudentNotesRoute,
  StudentAppStudentPlannerRoute: StudentAppStudentPlannerRoute,
  StudentAppStudentProfileSettingsRoute: StudentAppStudentProfileSettingsRoute,
  StudentAppStudentProgressRoute: StudentAppStudentProgressRoute,
  StudentAppStudentWelzijnRoute: StudentAppStudentWelzijnRoute,
}

const StudentAppRouteWithChildren = StudentAppRoute._addFileChildren(
  StudentAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  StudentAppRoute: StudentAppRouteWithChildren,
  AdminRoute: AdminRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
